[package]
name = "burn-vae-gan"
version = "0.1.0"
edition = "2024"
description = "A toy project for practicing `burn` by implementing a VAE+GAN generator with MNIST dataset"

[dependencies]
burn = { version = "0.18.0", features = [
    "wgpu",
    "train",
    "vision",
] }
image = "0.25.6"
